version: '3.9'

services:
  nginx:
    image: nginx:latest
    container_name: my_nginx
    ports:
      - "80:80"      # HTTP
      - "443:443"    # HTTPS
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d   # eigene Konfigurationen
      - ./nginx/html:/usr/share/nginx/html # Webinhalte
      - ./nginx/certs:/etc/nginx/certs     # SSL-Zertifikate (optional)
    restart: always

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
    environment:
      TZ: 'Europe/Berlin'
      # WEBPASSWORD: 'set a secure password here or it will be random'
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

  portainer:
    image: portainer/portainer-ce
    ports:
     - 9000:9000
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - ./portainer_data:/data
    restart: always

  watchtower:
    image: containrrr/watchtower
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock

volumes:
  portainer_data:

networks:
  lab_net:
    driver: bridge
