version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: my_nginx
    ports:
      - "80:80"      # HTTP
      - "443:443"    # HTTPS
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d   # eigene Konfigurationen
      - ./nginx/html:/usr/share/nginx/html # Webinhalte
      - ./nginx/certs:/etc/nginx/certs     # SSL-Zertifikate (optional)
    restart: always
